all: acaddom tests

tests: tst_mdl tst_mse tst_mus tst_psg tst_rast tst_sfx

src\tst_bmp.o: src\tst_bmp.c src\tst_bmp.h src\scrn.h src\types.h
	cc68x -g -c src\tst_bmp.c

tst_mdl: src\model.o src\effects.o src\events.o src\ints.o src\psg.o src\rast_asm.o src\tst_mdl.o src\test.o src\types.h
	cc68x -g src\model.o src\effects.o src\events.o src\ints.o src\psg.o src\rast_asm.o src\tst_mdl.o src\test.o -o bin\tst_mdl.tos

src\tst_mdl.o: src\tst_mdl.c src\effects.h src\model.h src\test.h
	cc68x -g -c src\tst_mdl.c

tst_mse: src\tst_mse.o src\in_asm.o src\input.o src\ints.o src\vector.o
	cc68x -g src\tst_mse.o src\in_asm.o src\input.o src\ints.o src\vector.o -o bin\tst_mse.tos

src\tst_mse.o: src\tst_mse.c src\bool.h src\input.h src\types.h
	cc68x -g -c src\tst_mse.c

tst_mus: src\tst_mus.o src\ints.o src\music.o src\psg.o src\rast_asm.o src\test.o
	cc68x -g src\tst_mus.o src\ints.o src\music.o src\psg.o src\rast_asm.o src\test.o -o bin\tst_mus.tos

src\tst_mus.o: src\tst_mus.c src\music.h src\psg.h src\test.h src\types.h
	cc68x -g -c src\tst_mus.c

tst_psg: src\psg.o src\raster.o src\rast_asm.o src\test.o src\tst_psg.o
	cc68x -g src\psg.o src\raster.o src\rast_asm.o src\test.o src\tst_psg.o -o bin\tst_psg.tos

src\tst_psg.o: src\tst_psg.c src\psg.h src\raster.h src\test.h src\types.h
	cc68x -g -c src\tst_psg.c

tst_rast: src\test.o src\tst_bmp.o src\tst_rast.o src\raster.o src\rast_asm.o
	cc68x -g src\test.o src\tst_bmp.o src\tst_rast.o src\raster.o src\rast_asm.o -o bin\tst_rast.tos

src\tst_rast.o: src\tst_rast.c src\raster.h src\tst_bmp.h src\scrn.h src\types.h
	cc68x -g -c src\tst_rast.c

tst_sfx: src\tst_sfx.o src\psg.o src\effects.o src\rast_asm.o src\test.o
	cc68x -g src\tst_sfx.o src\psg.o src\rast_asm.o src\effects.o src\test.o -o bin\tst_sfx.tos

src\tst_sfx.o: src\tst_sfx.c src\psg.h src\effects.h src\test.h
	cc68x -g -c src\tst_sfx.c

src\test.o: src\test.c src\test.h src\bool.h src\raster.h src\types.h
	cc68x -g -c src\test.c

acaddom: src\acaddom.o src\bitmaps.o src\effects.o src\events.o src\font16.o src\input.o src\in_asm.o src\ints.o src\model.o src\music.o src\psg.o src\raster.o src\rast_asm.o src\renderer.o src\vbl.o src\vector.o
	cc68x -g src\acaddom.o src\bitmaps.o src\effects.o src\events.o src\font16.o src\input.o src\in_asm.o src\ints.o src\model.o src\music.o src\psg.o src\raster.o src\rast_asm.o src\renderer.o src\vbl.o src\vector.o -o bin\acaddom.tos

src\vbl.o:	src\vbl.s src\vbl.h
	gen -D -L2 src\vbl.s

src\ints.o: src\ints.s src\ints.h
	gen -D -L2 src\ints.s

src\vector.o: src\vector.c src\vector.h
	cc68x -g -c src\vector.c

src\effects.o: src\effects.c src\effects.h src\psg.h
	cc68x -g -c src\effects.c

src\music.o: src\music.c src\music.h src\ints.h src\psg.h src\types.h
	cc68x -g -c src\music.c

src\psg.o: src\psg.h src\num_util.h src\toggle.h src\types.h
	cc68x -g -c src\psg.c

src\acaddom.o: src\acaddom.c src\bool.h src\events.h src\input.h src\model.h src\music.h src\types.h
	cc68x -g -c src\acaddom.c

src\in_asm.o: src\in_asm.s src\bool.h
	gen -D -L2 src\in_asm.s

src\input.o: src\input.c src\input.h src\ints.h src\types.h src\vector.h
	cc68x -g -c src\input.c

src\renderer.o: src\renderer.c src\renderer.h src\bitmaps.h src\bool.h src\font16.h src\model.h src\raster.h src\types.h
	cc68x -g -c src\renderer.c

src\raster.o: src\raster.c src\raster.h src\bool.h src\scrn.h src\types.h
	cc68x -g -c src\raster.c

src\font16.o: src\font16.c src\font16.h src\types.h
	cc68x -g -c src\font16.c

src\bitmaps.o: src\bitmaps.c src\bitmaps.h src\types.h src\model.h
	cc68x -g -c src\bitmaps.c

src\events.o: src\events.c src\events.h src\effects.h src\ints.h src\model.h
	cc68x -g -c src\events.c

src\model.o: src\model.c src\model.h src\bool.h src\events.h src\font16.h src\scrn.h src\types.h
	cc68x -g -c src\model.c

src\rast_asm.o: src\rast_asm.s
	gen -D -L2 src\rast_asm.s

