all: acaddom tst_mse

tst_mse: tst_mse.o in_asm.o input.o ints.o vector.o
	cc68x -g tst_mse.o in_asm.o input.o ints.o vector.o -o tst_mse.tos

tst_mse.o: tst_mse.c bool.h input.h types.h
	cc68x -g -c tst_mse.c

acaddom: acaddom.o bitmaps.o effects.o events.o font16.o input.o in_asm.o ints.o model.o music.o psg.o raster.o rast_asm.o renderer.o vbl.o vector.o
	cc68x -g acaddom.o bitmaps.o effects.o events.o font16.o input.o in_asm.o ints.o model.o music.o psg.o raster.o rast_asm.o renderer.o vbl.o vector.o -o acaddom.tos

vbl.o:	vbl.s vbl.h
	gen -D -L2 vbl.s

ints.o: ints.s ints.h
	gen -D -L2 ints.s

vector.o: vector.c vector.h
	cc68x -g -c vector.c

effects.o: effects.c effects.h psg.h
	cc68x -g -c effects.c

music.o: music.c music.h ints.h psg.h types.h
	cc68x -g -c music.c

psg.o: psg.h num_util.h toggle.h types.h
	cc68x -g -c psg.c

acaddom.o: acaddom.c bool.h events.h input.h model.h music.h types.h
	cc68x -g -c acaddom.c

in_asm.o: in_asm.s bool.h
	gen -D -L2 in_asm.s

input.o: input.c input.h ints.h types.h vector.h
	cc68x -g -c input.c

renderer.o: renderer.c renderer.h bitmaps.h bool.h font16.h model.h raster.h types.h
	cc68x -g -c renderer.c

raster.o: raster.c raster.h bool.h scrn.h types.h
	cc68x -g -c raster.c

font16.o: font16.c font16.h types.h
	cc68x -g -c font16.c

bitmaps.o: bitmaps.c bitmaps.h types.h model.h
	cc68x -g -c bitmaps.c

events.o: events.c events.h effects.h ints.h model.h
	cc68x -g -c events.c

model.o: model.c model.h bool.h events.h font16.h scrn.h types.h
	cc68x -g -c model.c

rast_asm.o: rast_asm.s
	gen -D -L2 rast_asm.s

